---
services:
  mcp-server:
    build:
      context: .
      args:
        VERSION: ${GIT_TAG:-latest}
    image: nicholaswilde/mcp-server:${GIT_TAG:-latest}
    ports:
      - "8080:8080"
    volumes:
      - ./agents-library:/app/agents-library
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - SERVER_PORT=${SERVER_PORT:-8080}
      - AGENTS_LIBRARY_PATH=${AGENTS_LIBRARY_PATH:-/app/agents-library}
      - MCP_SERVER_NAME=${MCP_SERVER_NAME:-mcp-server}
      - MCP_SERVER_STREAMABLE_HTTP_PATH=${MCP_SERVER_STREAMABLE_HTTP_PATH:-/}
      - MCP_SERVER_JSON_RESPONSE=${MCP_SERVER_JSON_RESPONSE:-true}
    restart: unless-stopped
