version: '3.8'

services:
  mcp-server:
    build:
      context: .
      args:
        VERSION: ${GIT_TAG:-latest}
    image: nicholaswilde/mcp-server:${GIT_TAG:-latest}
    ports:
      - "8080:8080"
    volumes:
      - ./agents-library:/app/agents-library
    environment:
      - AGENTS_LIBRARY_PATH=/app/agents-library
    restart: unless-stopped
