name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
      - '**/*.sh'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.py'
      - '**/*.sh'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        PYTHONPATH=$GITHUB_WORKSPACE pytest $GITHUB_WORKSPACE/tests/
