name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
      - '**/*.sh'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.py'
      - '**/*.sh'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools # Install pip-tools first
        pip-compile requirements.in
        pip-sync
    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run linting and formatting checks
      run: |
        task lint
    - name: Run tests
      run: |
        PYTHONPATH=$GITHUB_WORKSPACE pytest $GITHUB_WORKSPACE/tests/test_server.py
